<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPx3nukz\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPx3nukz/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPx3nukz.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerPx3nukz\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerPx3nukz\appProdProjectContainer([
    'container.build_hash' => 'Px3nukz',
    'container.build_id' => 'f9cf1bd1',
    'container.build_time' => 1682120929,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPx3nukz');
