<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOic5q5r\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOic5q5r/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerOic5q5r.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerOic5q5r\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerOic5q5r\appDevDebugProjectContainer([
    'container.build_hash' => 'Oic5q5r',
    'container.build_id' => '4d616e5d',
    'container.build_time' => 1686628335,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOic5q5r');
